spring:
  application:
    name: virtual-store

  datasource:
    url: jdbc:postgresql://localhost:5432/tienda_virtual
    username: kikecorpus
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

springdoc:
   # ── Documentación JSON ──────────────────────────────────────
  api-docs:
    enabled: true
    path: /api-docs              # → http://localhost:8080/api-docs

  # ── Swagger UI ──────────────────────────────────────────────
  swagger-ui:
    enabled: true
    path: /swagger-ui.html       # → http://localhost:8080/swagger-ui.html
    tags-sorter: alpha            # ordena los grupos alfabéticamente
    operations-sorter: alpha      # ordena los endpoints alfabéticamente
    display-request-duration: true # muestra el tiempo de cada request
    try-it-out-enabled: true      # habilita "Try it out" por defecto
    filter: true                  # habilita el buscador de endpoints

  # ── Paginación ──────────────────────────────────────────────
  pageable-as-query-param: true   # muestra page, size, sort como campos individuales

  # ── Modelos ─────────────────────────────────────────────────
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  show-actuator: false            # oculta endpoints de actuator si los tienes
  model-and-view-allowed: false

# ---------------------------------------------------------------
# JWT
# ---------------------------------------------------------------
jwt:
  # ✅ Mínimo 32 caracteres para HS256. En producción usa una variable
  # de entorno: jwt.secret=${JWT_SECRET}
  secret: "cambia-esto-por-un-secreto-seguro-32chars!"

  # Expiración del token en milisegundos
  # 86400000  =  24 horas
  # 3600000   =   1 hora
  expiration: 86400000

# ---------------------------------------------------------------
# CORS
# ---------------------------------------------------------------
cors:
  # En producción reemplaza con la URL real de tu frontend:
  # allowed-origin=${FRONTEND_URL}
  allowed-origin: "http://localhost:5173"

mercadopago:
  access-token: APP_USR-8984698397446586-052117-c9ed8623c760bdca521756e6dd38cde0-2132120273
  success-url: http://localhost:8080/api/payments/success
  failure-url: http://localhost:8080/api/payments/failure
  pending-url: http://localhost:8080/api/payments/pending